model_name: 'MultiTaskDeiT_patch16_tiny'
experiment_name: 'coloring_task'

model_name: 'MultiTaskDeiT_tiny'
data_path: 'data'
jigsaw_patches: 2
pixel_shuffle: False
verbose: true
img_size: 224
batch_size: 32
epochs: 50
weights: 'lossweights/weights.npy'
n_workers: 0


active_heads:
    coloring: true
    classification: false
    jigsaw: false

pretrained_info:
    checkpoint_type: 'timm_name'         # can either be 'torch_checkpoint' or 'timm_name'
    link: 'deit_tiny_patch16_224'


pixel_shuffle_cfg:
    do: true
    steps: 1
    smoothing: false

freeze_modules:
    cls_token: true
    pos_embed: true
    patch_embed: true
    blocks: true
    norm: true
    jigsaw_head: false
    coloring_decoder: false
    class_head: false


unfreeze_modules:
    cls_token: false
    pos_embed: false
    patch_embed: false
    blocks: false
    norm: false
    jigsaw_head: false
    coloring_decoder: false
    class_head: false




