model_name: 'MultiTaskDeiT_patch16_tiny'
experiment_name: 'jigsaw_2by2_224_full'
data_path: 'coco_colors'
verbose: true
img_size: 224
batch_size: 32
epochs: 50
lr : 0.0005 # 0.0001 when backbone unfrozen, 0.001 when backbone frozen
weights: 'lossweights/weights_25_bins_sigma_3_coco.npy'
n_workers: 10


active_heads:
    coloring: false
    classification: false
    jigsaw: true

pretrained_info:
    checkpoint_type: 'torch_checkpoint'         # can either be 'torch_checkpoint' or 'timm_name'
    link: 'checkpoint_jigsaw.pth'


pixel_shuffle_cfg:
    do: false
    steps: 1
    smoothing: false

jigsaw_cfg:
    use_cls_embeds: true
    n_jigsaw_patches: 2

freeze_modules:
    cls_token: false
    pos_embed: false
    patch_embed: false
    blocks: false
    norm: false
    jigsaw_head: false
    coloring_decoder: false
    class_head: false


unfreeze_modules:
    cls_token: false
    pos_embed: false
    patch_embed: false
    blocks: false
    norm: false
    jigsaw_head: false
    coloring_decoder: false
    class_head: false




