model_name: 'MultiTaskDeiT_patch16_tiny'
experiment_name: 'coloring_task'
data_path: 'data'
verbose: true
img_size: 224
batch_size: 32
epochs: 50
lr : 1e-3 # 1e-4 when backbone unfrozen
weights: 'lossweights/weights.npy'
n_workers: 0


active_heads:
    coloring: false
    classification: false
    jigsaw: true

pretrained_info:
    checkpoint_type: 'torch_checkpoint'         # can either be 'torch_checkpoint' or 'timm_name'
    link: 'checkpoint_jigsaw.pth'


pixel_shuffle_cfg:
    do: true
    steps: 1
    smoothing: false

jigsaw_cfg:
    use_cls_embeds: true
    n_jigsaw_patches: 2

freeze_modules:
    cls_token: false
    pos_embed: false
    patch_embed: false
    blocks: false
    norm: false
    jigsaw_head: false
    coloring_decoder: false
    class_head: false


unfreeze_modules:
    cls_token: false
    pos_embed: false
    patch_embed: false
    blocks: false
    norm: false
    jigsaw_head: false
    coloring_decoder: false
    class_head: false




